# Generated by Django 2.2 on 2019-04-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20190312_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.SlugField(choices=[('---', 'Unknown'), ('ON', 'On'), ('OFF', 'Off'), ('RES', 'Restarting'), ('LOC', 'Locked')], default='---', help_text="This should represent the current state of the device. <br>In most cases it should be set automatically if a working 'check_status' function is defined for the device type. <br>If this is not the case it should be set manually to 'On' if its turned on and you expect the device to be available for claiming by a build agent.", max_length=20, verbose_name='device_status'),
        ),
    ]
